// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPIDyCamMIrXq5_d5L0Hc9DnjHWp514qc',
    appId: '1:966775592131:web:9072a1cf2e3edb3a08fe76',
    messagingSenderId: '966775592131',
    projectId: 'psip-app-87783',
    authDomain: 'psip-app-87783.firebaseapp.com',
    storageBucket: 'psip-app-87783.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlMSVR6fm-5lHhcLW15iql8XNNMjWcKO4',
    appId: '1:966775592131:android:af3d3935ce31b69808fe76',
    messagingSenderId: '966775592131',
    projectId: 'psip-app-87783',
    storageBucket: 'psip-app-87783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD8xPcU_VskXbfYHvtXTeMQqVj9hx48E0',
    appId: '1:966775592131:ios:45cca47119033e8d08fe76',
    messagingSenderId: '966775592131',
    projectId: 'psip-app-87783',
    storageBucket: 'psip-app-87783.appspot.com',
    iosBundleId: 'com.example.psipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD8xPcU_VskXbfYHvtXTeMQqVj9hx48E0',
    appId: '1:966775592131:ios:45cca47119033e8d08fe76',
    messagingSenderId: '966775592131',
    projectId: 'psip-app-87783',
    storageBucket: 'psip-app-87783.appspot.com',
    iosBundleId: 'com.example.psipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPIDyCamMIrXq5_d5L0Hc9DnjHWp514qc',
    appId: '1:966775592131:web:6da4dcb782052ac308fe76',
    messagingSenderId: '966775592131',
    projectId: 'psip-app-87783',
    authDomain: 'psip-app-87783.firebaseapp.com',
    storageBucket: 'psip-app-87783.appspot.com',
  );
}
